### ISSUE TITLE
Additional Vertex Module in 2.4.1

### ISSUE THREAD

**Issue by pauldonnelly** [yireo/magento2-replace-bundled#16]
Jisse, it looks like module-address-validation-api needs to be included along side the Vertex modules. When bin/magento s:up is ran it throws the following error:

PHP Fatal error:  Interface 'Vertex\Data\AddressInterface' not found in ../vendor/vertex/module-address-validation-api/Api/Data/AddressInterface.php on line 18

I assume removing module-address-validation-api along with the other modules will fix this.

**Comment by jissereitsma** [comment]
Thanks for addressing this. In none of my environments, with or without this replacement used, I can find a package named `vertex/module-address-validation-api`. Is this the Magento Commerce edition you are referring to?

**Comment by jissereitsma** [comment]
Scrap that. It is simplythere in M2.4.1 CE. I'll add a commit to this. Please note that you are welcome to make PRs as well :) About the same amount of work: https://github.com/yireo/magento2-replace-bundled/commit/ec57d506abc1b97e825ae0f3ee9f40097b4367b6

**Comment by jissereitsma** [comment]
https://github.com/yireo/magento2-replace-bundled/releases/tag/4.1.3

**Comment by Aquive** [comment]
What is the best way to use this tag? When I do  `composer require yireo/magento2-replace-bundled:^4.1 --no-update ` It doesn't get the packages with this fix.

**Comment by jissereitsma** [comment]
@Aquive If you are talking about the module `vertex/module-address-validation-api`, it is already included in the release 4.1.1 of this replacement package: https://github.com/yireo/magento2-replace-bundled/blob/4.1.4/composer.json#L35 Which exact version did you install and which packages are not replaced yet?

**Comment by Aquive** [comment]
@jissereitsma thanks for your swift reply. I am not so familiar with requiring a specific tag. I saw it was included in the 4.1.3 tag.

What is tried is both:

`composer require yireo/magento2-replace-bundled:^4.0 --no-update`
`composer update --no-lock`

and

`composer require yireo/magento2-replace-bundled:^4.1 --no-update`
`composer update --no-lock`

Magento version is 2.4.1 btw.

**Comment by jissereitsma** [comment]
If you run `composer show yireo/magento2-replace-bundle`, which version is reported? Likewise, which Vertex packages are still there? `composer show | grep vertex`

**Comment by Aquive** [comment]
I switched to a manual solution after some other problems. I would have liked to answer your question. But cannot anymore since I moved on. Thanks for the support!

**Comment by jissereitsma** [comment]
Ok, then I'll close this issue for now. Feel free to re-open if this problem still exists. Or open another issue for another problem.
