### ISSUE TITLE
Magento 2.4.3-p2 update issue

### ISSUE THREAD

**Issue by nix0x00** [yireo/magento2-replace-bundled#26]
Hi, 

I have placed these module in replace config of composer.json but then upon `composer update` I am getting following errors.

 Problem 1
    - magento/project-community-edition 2.4.3 requires magento/product-community-edition 2.4.3 -> satisfiable by magento/product-community-edition[2.4.3] but these conflict with
your requirements or minimum-stability.
    - magento/product-community-edition 2.4.3-p3 requires paypal/module-braintree 4.2.5 -> satisfiable by paypal/module-braintree[4.2.5].
    - magento/product-community-edition 2.4.3-p3 requires paypal/module-braintree 4.2.5 -> satisfiable by paypal/module-braintree[4.2.5].
    - paypal/module-braintree 4.2.5 requires paypal/module-braintree-core 4.2.5 -> satisfiable by paypal/module-braintree-core[4.2.5].
    - paypal/module-braintree 4.2.5 requires paypal/module-braintree-core 4.2.5 -> satisfiable by paypal/module-braintree-core[4.2.5].
    - paypal/module-braintree-core 4.2.5 conflicts with magento/project-community-edition[2.4.3].
    - magento/project-community-edition 2.4.3 conflicts with paypal/module-braintree-core[4.2.5].
    - Installation request for magento/project-community-edition 2.4.3 -> satisfiable by magento/project-community-edition[2.4.3].
    - Installation request for magento/product-community-edition 2.4.3-p3 -> satisfiable by magento/product-community-edition[2.4.3-p3].

**Comment by nix0x00** [comment]
I debugged and finally noticed one mistake i.e. I forgot to add following modules to replace config. After adding these everything worked fine.

    "paypal/module-braintree": "*",
    "paypal/module-braintree-core": "*",
    "paypal/module-braintree-graph-ql": "*",


@jissereitsma please close the ticket. and thanks for such great extensions.

**Comment by jissereitsma** [comment]
I'll close the ticket. But before that, I'm wondering still what went wrong here. The latest version of this module its replacements (https://github.com/yireo/magento2-replace-bundled/blob/4.3.2/composer.json) mention the very modules that you posted (`paypal/*`). Are you not using this latest version 4.3.2 of this replacement package?

(Minor note: This is not a module, but a composer package.)
