### ISSUE TITLE
Magento 2.4.6 update

### ISSUE THREAD

**Issue by Stevie-Ray** [yireo/magento2-replace-bundled#27]
While updating a project to the latest Magento version and using the replace modules I got the following error; 

Can't install  yireo/magento2-replace-graphql because of yireo/magento2-replace-bundled. They both replace klarna/module-kp-graph-ql and thus cannot coexist.

This is the same for:
magento/module-braintree-graph-ql
paypal/module-braintree-graph-ql

Is this intended behavior?

**Comment by jissereitsma** [comment]
No, this is a shortcoming of composer replacements. You can't replace things twice. Take your pick and move the replacements towards your own root `composer.json` file :(
