### ISSUE TITLE
Remove PayPal 

### ISSUE THREAD

**Issue by henkvalk** [yireo/magento2-replace-bundled#28]
I don't know if this is a replacement for bundled, or for core, but removing paypal completely as payment method seems to be better. A lot of PSP's like Adyen, Mollie, Stripe etc having PayPal as Payment option. So unnecessary and replacealbe 

```
        "magento/module-paypal": "*",
        "magento/module-paypal-captcha": "*",
        "magento/module-re-captcha-paypal": "*",
        "magento/module-paypal-graph-ql": "*",
```

**Comment by jissereitsma** [comment]
This is a difficult one. Adding these lines to Magento instances that are running older versions will most likely break them. So I'm not sure if this should be included.

**Comment by henkvalk** [comment]
Ok, I see `adyen/module-payment` is requiring the `magento/module-paypal`, but also using the `magento/module-multishipping`.  They are requiring the PayPal module because they extends the Billing Agreement class.

**Comment by jissereitsma** [comment]
Sadly, yes. As of yet, I'm closing this issue :( Unhappily.
