### ISSUE TITLE
Some modules from replace-core should be here too

### ISSUE THREAD

**Issue by robbertstevens** [yireo/magento2-replace-bundled#5]
Maybe we should add the following packages from magento2-replace-core in this one too:

- "magento/module-fedex": "*",
- "magento/module-eway": "*",
- "magento/module-dhl": "*",
- "magento/module-ups": "*",
- "magento/module-worldpay": "*"
- "magento/module-signifyd": "*",
- "magento/google-shopping-ads": "*",
- "magento/module-authorizenet": "*",
- "magento/module-authorizenet-acceptjs": "*",
- "magento/module-authorizenet-cardinal": "*",
- "magento/module-authorizenet-graph-ql": "*",
- "magento/module-cybersource": "*",

**Comment by lewisje** [comment]
It also looks like these modules, new to Magento 2.3.4, fit the pattern:

    "magento/module-adobe-ims": "*",
    "magento/module-adobe-ims-api": "*",
    "magento/module-adobe-stock-admin-ui": "*",
    "magento/module-adobe-stock-asset": "*",
    "magento/module-adobe-stock-asset-api": "*",
    "magento/module-adobe-stock-client": "*",
    "magento/module-adobe-stock-client-api": "*",
    "magento/module-adobe-stock-image": "*",
    "magento/module-adobe-stock-image-admin-ui": "*",
    "magento/module-adobe-stock-image-api": "*",

**Comment by jissereitsma** [comment]
Correct. Happy to see pull requests for this. Otherwise I will pick this up in 2 weeks time.

**Comment by jissereitsma** [comment]
@lewisje See https://github.com/yireo/magento2-replace-core/blob/magento-2.3.4/composer.json

@robbertstevens No, this wouldn't be a good idea. The `magento2-replace-core` package is meant to replace core features developed by Magento (which is Adobe), while the `magento2-replace-bundled` package is meant to replace third party extensions that are bundled with the core. You can install both packages though.
