### ISSUE TITLE
Suggestion for removal from 2.3.4

### ISSUE THREAD

**Issue by n2diving-net** [yireo/magento2-replace-bundled#7]
Adobe Stock Photo Integration
---------------------------------------------------
Magento_AdobeIms
Magento_AdobeImsApi
Magento_AdobeStockAdminUi
Magento_AdobeStockAsset
Magento_AdobeStockAssetApi
Magento_AdobeStockClient
Magento_AdobeStockClientApi
Magento_AdobeStockImage
Magento_AdobeStockImageAdminUi
Magento_AdobeStockImageApi

**Comment by jissereitsma** [comment]
See https://github.com/yireo/magento2-replace-core/blob/magento-2.3.4/composer.json
